name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build with Maven
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET_KEY }}
          DB_URL: ${{ secrets.DB_URL }}
        run: mvn -f ./backend/pom.xml clean package -Dmaven.test.skip=true

      - name: Zip application for deployment
        run: |
          cd backend
          zip -r ../deploy.zip .

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "URL Shortener"
          environment_name: "URLShortener-env"
          version_label: "deploy-${{ github.run_number }}"
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip